#!/bin/sh

nodeswitchUnameM=$(uname -m)
if [ "$nodeswitchUnameM" != "x86_64" ] && [ "$nodeswitchUnameM" != "aarch64" ]; then
    echo "This utility is only for Linux x64 and ARM64"
    exit 1
fi

mkdir -p "$HOME/.local/share/nodeswitch"

mkdir -p "$HOME/.local/bin"
curl -s https://raw.githubusercontent.com/alexsch01/nodeswitch-linux/main/nodeswitch > "$HOME/.local/bin/nodeswitch"
curl -s https://raw.githubusercontent.com/alexsch01/nodeswitch-linux/main/nodeswitch.sh > "$HOME/.local/bin/nodeswitch.sh"
chmod +x "$HOME/.local/bin/nodeswitch"

if ! grep -R 'alias nodeswitch=' "$HOME/.bashrc" > /dev/null; then
    echo 'alias nodeswitch="source nodeswitch"' >> "$HOME/.bashrc"
fi

echo "nodeswitch program install finished"
echo "- $HOME/.local/bin needs to be in the PATH variable"
