#!/bin/sh

mkdir -p "$HOME/.local/share/nodeswitch"

mkdir -p "$HOME/.local/bin"
curl -s https://raw.githubusercontent.com/alexsch01/nodeswitch-linux/main/nodeswitch > "$HOME/.local/bin/nodeswitch"
curl -s https://raw.githubusercontent.com/alexsch01/nodeswitch-linux/main/nodeswitch.sh > "$HOME/.local/bin/nodeswitch.sh"
chmod +x "$HOME/.local/bin/nodeswitch"
chmod +x "$HOME/.local/bin/nodeswitch.sh"

if ! grep -R 'alias nodeswitch="source nodeswitch.sh"' "$HOME/.bashrc" > /dev/null;
        echo 'alias nodeswitch="source nodeswitch.sh"' >> "$HOME/.bashrc"
fi

echo "nodeswitch program install finished"
echo "- $HOME/.local/bin needs to be in the PATH variable"
